apiVersion: v1
kind: Service
metadata:
  name: worker-app-service
  labels:
    name: worker-app-service
    app: demo-voting-app
spec:
  selector:
    name: worker-app-pod
    app: demo-voting-app
  ports:
  - targetPort: 80
    port: 80
